# GitHub Actions for hexo on GitHub Pages
# https://hexo.io/zh-cn/docs/github-pages.html

name: Build Hexo Pages

on:
  push:
    branches:
      - hexo  # default branch

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # If your repository depends on submodule, please see: https://github.com/actions/checkout
          submodules: recursive

      - name: Use Node.js 7
        uses: actions/setup-node@v2
        with:
          node-version: '7'

      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache

      # Install Dependencies
      # install pandoc which is required by `hexo-renderer-pandoc`
      - run: wget https://github.com/jgm/pandoc/releases/download/2.7.3/pandoc-2.7.3-1-amd64.deb
      - run: sudo dpkg -i pandoc-2.7.3-1-amd64.deb
      # `npm ci` is better than `npm install`
      - run: npm ci

      - name: Build
        run: hexo g

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
